### ISSUE TITLE
[BUG] TypeError in filter_key_set

### ISSUE THREAD

**Issue by fkantelberg** [icgood/pymap#158]
Hello again,

I guess I found the same error again. Please see my setup below.

**Server:**
```console
docker run --rm -it -p 4143:143 pymap:latest --debug --no-tls dict --demo-data --demo-user test@example.org --demo-password test
```

**Client:**
```python
from imaplib import IMAP4

with IMAP4("localhost", port=4143) as mbox:
    mbox.login('test@example.org', 'test')
    mbox.list()
    mbox.select("inbox")
    mbox.search(None, '(FROM "LDJ")')
```

**Exception:**
```
Traceback (most recent call last):
  File "/pymap/pymap/imap/__init__.py", line 124, in __call__
    await conn.run(state)
  File "/pymap/pymap/imap/__init__.py", line 336, in run
    await self._run_state(state)
  File "/pymap/pymap/imap/__init__.py", line 372, in _run_state
    response = await self._exec(state.do_command(cmd))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pymap/pymap/imap/state.py", line 403, in do_command
    response, selected = await func(cmd)
                         ^^^^^^^^^^^^^^^
  File "/pymap/pymap/imap/state.py", line 325, in do_search
    messages, updates = await self.session.search_mailbox(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pymap/pymap/backend/session.py", line 228, in search_mailbox
    req = FetchRequirement.reduce(key.requirement for key in keys)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pymap/pymap/parsing/specials/fetchattr.py", line 89, in reduce
    return reduce(lambda x, y: x | y, requirements, cls.NONE)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pymap/pymap/backend/session.py", line 228, in <genexpr>
    req = FetchRequirement.reduce(key.requirement for key in keys)
                                  ^^^^^^^^^^^^^^^
  File "/pymap/pymap/parsing/specials/searchkey.py", line 68, in requirement
    keyset_reqs = {key.requirement for key in self.filter_key_set}
                                              ^^^^^^^^^^^^^^^^^^^
  File "/pymap/pymap/parsing/specials/searchkey.py", line 98, in filter_key_set
    return self._get_filter(frozenset)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pymap/pymap/parsing/specials/searchkey.py", line 89, in _get_filter
    raise TypeError(self.filter)
TypeError: (<pymap.parsing.specials.searchkey.SearchKey object at 0x7f5f94fce2d0>,)
```

This line isn't currently covered by the tests. Changing it to tuple would mean changing the typing all over the place. I guess you have to look into it and I sadly can't provide a patch myself.

**Comment by icgood** [comment]
Fixed and added test coverage, thanks for the report!
