### ISSUE TITLE
PyPI v0.7.1 fail to install

### ISSUE THREAD

**Issue by chenliangomc** [icgood/pymap#38]
```
$ pip install pymap
Collecting pymap
  Downloading https://files.pythonhosted.org/packages/25/86/2a4c44af4b032b4c1df8b12dce54b226ad17cf94124252885281288bfeb8/pymap-0.7.1.tar.gz (110kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-uWVCUh/pymap/setup.py", line 26
        setup(**conf_dict['metadata'], **conf_dict['options'])
                                     ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-uWVCUh/pymap/
```

**Comment by icgood** [comment]
Thanks for the heads up. Unfortunately I did not correctly indicate that pymap is Python 3.7+ _only_ using the `python_requires` setup option. I've taken advantage of lots of the latest features in 3.7, so it won't be possible to maintain backwards compatibility with older versions.
